
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
// DTO 模型与数据层的实体 相互 转换工具 类
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


