//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransferObject
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;using Newtonsoft.Json;
    using System.Collections.Generic;
    
    [DataContract()]
    public partial class AddressDto 
    {
        [Key()] 
        [Required] 
        [DataMember] 
        public int AddressID  {get; set; }
     
        [Required] 
     
        [StringLength(60)]
        [DataMember] 
        public string AddressLine1  {get; set; }
     
        [StringLength(60)]
        [DataMember] 
        public string AddressLine2  {get; set; }
     
        [Required] 
     
        [StringLength(30)]
        [DataMember] 
        public string City  {get; set; }
     
        [Required] 
        [DataMember] 
        public int StateProvinceID  {get; set; }
     
        [Required] 
     
        [StringLength(15)]
        [DataMember] 
        public string PostalCode  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.Guid rowguid  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.DateTime ModifiedDate  {get; set; }
    
         public override string ToString()
         {
             return JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
         }
    }
}
