//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransferObject
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;using Newtonsoft.Json;
    using System.Collections.Generic;
    
    [DataContract()]
    public partial class ContactDto : UIPaging
    {
        [Key()] 
        [Required] 
        [DataMember] 
        public int ContactID  {get; set; }
     
        [Required] 
        [DataMember] 
        public bool NameStyle  {get; set; }
     
        [StringLength(8)]
        [DataMember] 
        public string Title  {get; set; }
     
        [Required] 
     
        [StringLength(50)]
        [DataMember] 
        public string FirstName  {get; set; }
     
        [StringLength(50)]
        [DataMember] 
        public string MiddleName  {get; set; }
     
        [Required] 
     
        [StringLength(50)]
        [DataMember] 
        public string LastName  {get; set; }
     
        [StringLength(10)]
        [DataMember] 
        public string Suffix  {get; set; }
     
        [StringLength(50)]
        [DataMember] 
        public string EmailAddress  {get; set; }
     
        [Required] 
        [DataMember] 
        public int EmailPromotion  {get; set; }
     
        [StringLength(25)]
        [DataMember] 
        public string Phone  {get; set; }
     
        [Required] 
     
        [StringLength(128)]
        [DataMember] 
        public string PasswordHash  {get; set; }
     
        [Required] 
     
        [StringLength(10)]
        [DataMember] 
        public string PasswordSalt  {get; set; }
        [DataMember] 
        public string AdditionalContactInfo  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.Guid rowguid  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.DateTime ModifiedDate  {get; set; }
    
        //[DataMember] 
        //[JsonProperty("Employeess")]
        //public virtual EmployeeDto [] Employeess { get; set; }
    
         public override string ToString()
         {
             return JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
         }
    }
}
