//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransferObject
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;using Newtonsoft.Json;
    using System.Collections.Generic;
    
    [DataContract()]
    public partial class ContactDto 
    {
        [Key()] 
        [Required] 
        [DataMember] 
        public int ContactID  {get; set; }
     
        [Required] 
        [DataMember] 
        public bool NameStyle  {get; set; }
     
        [StringLength(8)]
        [DataMember] 
        public string Title  {get; set; }
     
        [Required] 
     
        [StringLength(50)]
        [DataMember] 
        public string FirstName  {get; set; }
     
        [StringLength(50)]
        [DataMember] 
        public string MiddleName  {get; set; }
     
        [Required] 
     
        [StringLength(50)]
        [DataMember] 
        public string LastName  {get; set; }
     
        [StringLength(10)]
        [DataMember] 
        public string Suffix  {get; set; }
     
        [StringLength(50)]
        [DataMember] 
        public string EmailAddress  {get; set; }
     
        [Required] 
        [DataMember] 
        public int EmailPromotion  {get; set; }
     
        [StringLength(25)]
        [DataMember] 
        public string Phone  {get; set; }
     
        [Required] 
     
        [StringLength(128)]
        [DataMember] 
        public string PasswordHash  {get; set; }
     
        [Required] 
     
        [StringLength(10)]
        [DataMember] 
        public string PasswordSalt  {get; set; }
        [DataMember] 
        public string AdditionalContactInfo  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.Guid rowguid  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.DateTime ModifiedDate  {get; set; }
    
        //[DataMember] 
        //[JsonProperty("Employeess")]
        //public virtual EmployeeDto [] Employeess { get; set; }
    
         public override string ToString()
         {
             return JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
         }
    }
}
