//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntiies
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;using Newtonsoft.Json;
    using System.Collections.Generic;
    
    [DataContract()]
    public partial class EmployeePayHistoryDto : UIPaging
    {
        [Key] 
        [Required] 
        [DataMember] 
        public int EmployeeID  {get; set; }
        [Key] 
        [Required] 
        [DataMember] 
        public System.DateTime RateChangeDate  {get; set; }
     
        [Required] 
        [DataMember] 
        public decimal Rate  {get; set; }
     
        [Required] 
        [DataMember] 
        public byte PayFrequency  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.DateTime ModifiedDate  {get; set; }
    
        [DataMember] 
        [JsonProperty("Employee")]
        public virtual Employee Employee { get; set; }
    
         public override string ToString()
         {
             return JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
         }
    }
}
