// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPCEmployeeService.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace GRPCEmployeeService {
  public static partial class gRPC
  {
    static readonly string __ServiceName = "gRPCEmployeeService.gRPC";

    static readonly grpc::Marshaller<global::GRPCEmployeeService.GetEmployeeListRequest> __Marshaller_GetEmployeeListRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.GetEmployeeListRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCEmployeeService.GetEmployeeListResponse> __Marshaller_GetEmployeeListResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.GetEmployeeListResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCEmployeeService.GetEmployeeOneRequest> __Marshaller_GetEmployeeOneRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.GetEmployeeOneRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCEmployeeService.GetEmployeeOneReply> __Marshaller_GetEmployeeOneReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.GetEmployeeOneReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCEmployeeService.EditEmployeeRequest> __Marshaller_EditEmployeeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.EditEmployeeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCEmployeeService.EditEmployeeReply> __Marshaller_EditEmployeeReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.EditEmployeeReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCEmployeeService.RemoveEmployeeRequest> __Marshaller_RemoveEmployeeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.RemoveEmployeeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCEmployeeService.RemoveEmployeeReply> __Marshaller_RemoveEmployeeReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCEmployeeService.RemoveEmployeeReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GRPCEmployeeService.GetEmployeeListRequest, global::GRPCEmployeeService.GetEmployeeListResponse> __Method_GetEmployeeList = new grpc::Method<global::GRPCEmployeeService.GetEmployeeListRequest, global::GRPCEmployeeService.GetEmployeeListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetEmployeeList",
        __Marshaller_GetEmployeeListRequest,
        __Marshaller_GetEmployeeListResponse);

    static readonly grpc::Method<global::GRPCEmployeeService.GetEmployeeOneRequest, global::GRPCEmployeeService.GetEmployeeOneReply> __Method_GetOne = new grpc::Method<global::GRPCEmployeeService.GetEmployeeOneRequest, global::GRPCEmployeeService.GetEmployeeOneReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOne",
        __Marshaller_GetEmployeeOneRequest,
        __Marshaller_GetEmployeeOneReply);

    static readonly grpc::Method<global::GRPCEmployeeService.EditEmployeeRequest, global::GRPCEmployeeService.EditEmployeeReply> __Method_Edit = new grpc::Method<global::GRPCEmployeeService.EditEmployeeRequest, global::GRPCEmployeeService.EditEmployeeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Edit",
        __Marshaller_EditEmployeeRequest,
        __Marshaller_EditEmployeeReply);

    static readonly grpc::Method<global::GRPCEmployeeService.RemoveEmployeeRequest, global::GRPCEmployeeService.RemoveEmployeeReply> __Method_Remove = new grpc::Method<global::GRPCEmployeeService.RemoveEmployeeRequest, global::GRPCEmployeeService.RemoveEmployeeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Remove",
        __Marshaller_RemoveEmployeeRequest,
        __Marshaller_RemoveEmployeeReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GRPCEmployeeService.GRPCEmployeeServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of gRPC</summary>
    public abstract partial class gRPCBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GRPCEmployeeService.GetEmployeeListResponse> GetEmployeeList(global::GRPCEmployeeService.GetEmployeeListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GRPCEmployeeService.GetEmployeeOneReply> GetOne(global::GRPCEmployeeService.GetEmployeeOneRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GRPCEmployeeService.EditEmployeeReply> Edit(global::GRPCEmployeeService.EditEmployeeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GRPCEmployeeService.RemoveEmployeeReply> Remove(global::GRPCEmployeeService.RemoveEmployeeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for gRPC</summary>
    public partial class gRPCClient : grpc::ClientBase<gRPCClient>
    {
      /// <summary>Creates a new client for gRPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public gRPCClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for gRPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public gRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected gRPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected gRPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GRPCEmployeeService.GetEmployeeListResponse GetEmployeeList(global::GRPCEmployeeService.GetEmployeeListRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetEmployeeList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCEmployeeService.GetEmployeeListResponse GetEmployeeList(global::GRPCEmployeeService.GetEmployeeListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetEmployeeList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.GetEmployeeListResponse> GetEmployeeListAsync(global::GRPCEmployeeService.GetEmployeeListRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetEmployeeListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.GetEmployeeListResponse> GetEmployeeListAsync(global::GRPCEmployeeService.GetEmployeeListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetEmployeeList, null, options, request);
      }
      public virtual global::GRPCEmployeeService.GetEmployeeOneReply GetOne(global::GRPCEmployeeService.GetEmployeeOneRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOne(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCEmployeeService.GetEmployeeOneReply GetOne(global::GRPCEmployeeService.GetEmployeeOneRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOne, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.GetEmployeeOneReply> GetOneAsync(global::GRPCEmployeeService.GetEmployeeOneRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetOneAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.GetEmployeeOneReply> GetOneAsync(global::GRPCEmployeeService.GetEmployeeOneRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOne, null, options, request);
      }
      public virtual global::GRPCEmployeeService.EditEmployeeReply Edit(global::GRPCEmployeeService.EditEmployeeRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Edit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCEmployeeService.EditEmployeeReply Edit(global::GRPCEmployeeService.EditEmployeeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Edit, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.EditEmployeeReply> EditAsync(global::GRPCEmployeeService.EditEmployeeRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return EditAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.EditEmployeeReply> EditAsync(global::GRPCEmployeeService.EditEmployeeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Edit, null, options, request);
      }
      public virtual global::GRPCEmployeeService.RemoveEmployeeReply Remove(global::GRPCEmployeeService.RemoveEmployeeRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Remove(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCEmployeeService.RemoveEmployeeReply Remove(global::GRPCEmployeeService.RemoveEmployeeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Remove, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.RemoveEmployeeReply> RemoveAsync(global::GRPCEmployeeService.RemoveEmployeeRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RemoveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCEmployeeService.RemoveEmployeeReply> RemoveAsync(global::GRPCEmployeeService.RemoveEmployeeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Remove, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override gRPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new gRPCClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(gRPCBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetEmployeeList, serviceImpl.GetEmployeeList)
          .AddMethod(__Method_GetOne, serviceImpl.GetOne)
          .AddMethod(__Method_Edit, serviceImpl.Edit)
          .AddMethod(__Method_Remove, serviceImpl.Remove).Build();
    }

  }
}
#endregion
