   
 
 
 
 

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksModel    
{
    using System;
    public partial class AdventureWorksEntities : global::System.Data.Services.Client.DataServiceContext
    {
        public AdventureWorksEntities(global::System.Uri serviceRoot) : 
            base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V1)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        
    protected global::System.Type ResolveTypeFromName(string typeName)
    {
        if (typeName.StartsWith("AdventureWorksModel", global::System.StringComparison.Ordinal))
        {
            return this.GetType().Assembly.GetType(string.Concat("AdventureWorksModel", typeName.Substring(19)), false);
        }

        return null;
    }

    protected string ResolveNameFromType(global::System.Type clientType)
    {
       if (clientType.Namespace.Equals("AdventureWorksModel", global::System.StringComparison.Ordinal))
       {
           return string.Concat("AdventureWorksModel.", clientType.Name);
       }

       return null;
    }
        
        partial void OnContextCreated();
        
        public global::System.Data.Services.Client.DataServiceQuery<Employee> Employees
        {
            get
            {
                if ((this._Employees == null))
                {
                    this._Employees = base.CreateQuery<Employee>("Employees");
                }
                return this._Employees;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Employee> _Employees;        
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
        
        public global::System.Data.Services.Client.DataServiceQuery<EmployeePayHistory> EmployeePayHistories
        {
            get
            {
                if ((this._EmployeePayHistories == null))
                {
                    this._EmployeePayHistories = base.CreateQuery<EmployeePayHistory>("EmployeePayHistories");
                }
                return this._EmployeePayHistories;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<EmployeePayHistory> _EmployeePayHistories;        
        public void AddToEmployeePayHistories(EmployeePayHistory employeePayHistory)
        {
            base.AddObject("EmployeePayHistories", employeePayHistory);
        }
        
        public global::System.Data.Services.Client.DataServiceQuery<Contact> Contacts
        {
            get
            {
                if ((this._Contacts == null))
                {
                    this._Contacts = base.CreateQuery<Contact>("Contacts");
                }
                return this._Contacts;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Contact> _Contacts;        
        public void AddToContacts(Contact contact)
        {
            base.AddObject("Contacts", contact);
        }
        
    }
    
    [global::System.Data.Services.Common.EntitySetAttribute("Employees")]    
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID")]
    public partial class Employee : global::System.ComponentModel.INotifyPropertyChanged
    {
        public static Employee CreateEmployee (int employeeID , string nationalIDNumber , int contactID , string loginID , string title , global::System.DateTime birthDate , string maritalStatus , string gender , global::System.DateTime hireDate , bool salariedFlag , short vacationHours , short sickLeaveHours , bool currentFlag , global::System.Guid rowguid , global::System.DateTime modifiedDate)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.NationalIDNumber = nationalIDNumber;
            employee.ContactID = contactID;
            employee.LoginID = loginID;
            employee.Title = title;
            employee.BirthDate = birthDate;
            employee.MaritalStatus = maritalStatus;
            employee.Gender = gender;
            employee.HireDate = hireDate;
            employee.SalariedFlag = salariedFlag;
            employee.VacationHours = vacationHours;
            employee.SickLeaveHours = sickLeaveHours;
            employee.CurrentFlag = currentFlag;
            employee.rowguid = rowguid;
            employee.ModifiedDate = modifiedDate;
            return employee;
        }
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
                this.OnPropertyChanged("EmployeeID");
            }
        }             
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();

        public string NationalIDNumber
        {
            get
            {
                return this._NationalIDNumber;
            }
            set
            {
                this.OnNationalIDNumberChanging(value);
                this._NationalIDNumber = value;
                this.OnNationalIDNumberChanged();
                this.OnPropertyChanged("NationalIDNumber");
            }
        }             
        private string _NationalIDNumber;
        partial void OnNationalIDNumberChanging(string value);
        partial void OnNationalIDNumberChanged();

        public int ContactID
        {
            get
            {
                return this._ContactID;
            }
            set
            {
                this.OnContactIDChanging(value);
                this._ContactID = value;
                this.OnContactIDChanged();
                this.OnPropertyChanged("ContactID");
            }
        }             
        private int _ContactID;
        partial void OnContactIDChanging(int value);
        partial void OnContactIDChanged();

        public string LoginID
        {
            get
            {
                return this._LoginID;
            }
            set
            {
                this.OnLoginIDChanging(value);
                this._LoginID = value;
                this.OnLoginIDChanged();
                this.OnPropertyChanged("LoginID");
            }
        }             
        private string _LoginID;
        partial void OnLoginIDChanging(string value);
        partial void OnLoginIDChanged();

        public global::System.Nullable<int> ManagerID
        {
            get
            {
                return this._ManagerID;
            }
            set
            {
                this.OnManagerIDChanging(value);
                this._ManagerID = value;
                this.OnManagerIDChanged();
                this.OnPropertyChanged("ManagerID");
            }
        }             
        private global::System.Nullable<int> _ManagerID;
        partial void OnManagerIDChanging(global::System.Nullable<int> value);
        partial void OnManagerIDChanged();

        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }             
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();

        public global::System.DateTime BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                this.OnBirthDateChanging(value);
                this._BirthDate = value;
                this.OnBirthDateChanged();
                this.OnPropertyChanged("BirthDate");
            }
        }             
        private global::System.DateTime _BirthDate;
        partial void OnBirthDateChanging(global::System.DateTime value);
        partial void OnBirthDateChanged();

        public string MaritalStatus
        {
            get
            {
                return this._MaritalStatus;
            }
            set
            {
                this.OnMaritalStatusChanging(value);
                this._MaritalStatus = value;
                this.OnMaritalStatusChanged();
                this.OnPropertyChanged("MaritalStatus");
            }
        }             
        private string _MaritalStatus;
        partial void OnMaritalStatusChanging(string value);
        partial void OnMaritalStatusChanged();

        public string Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
                this.OnPropertyChanged("Gender");
            }
        }             
        private string _Gender;
        partial void OnGenderChanging(string value);
        partial void OnGenderChanged();

        public global::System.DateTime HireDate
        {
            get
            {
                return this._HireDate;
            }
            set
            {
                this.OnHireDateChanging(value);
                this._HireDate = value;
                this.OnHireDateChanged();
                this.OnPropertyChanged("HireDate");
            }
        }             
        private global::System.DateTime _HireDate;
        partial void OnHireDateChanging(global::System.DateTime value);
        partial void OnHireDateChanged();

        public bool SalariedFlag
        {
            get
            {
                return this._SalariedFlag;
            }
            set
            {
                this.OnSalariedFlagChanging(value);
                this._SalariedFlag = value;
                this.OnSalariedFlagChanged();
                this.OnPropertyChanged("SalariedFlag");
            }
        }             
        private bool _SalariedFlag;
        partial void OnSalariedFlagChanging(bool value);
        partial void OnSalariedFlagChanged();

        public short VacationHours
        {
            get
            {
                return this._VacationHours;
            }
            set
            {
                this.OnVacationHoursChanging(value);
                this._VacationHours = value;
                this.OnVacationHoursChanged();
                this.OnPropertyChanged("VacationHours");
            }
        }             
        private short _VacationHours;
        partial void OnVacationHoursChanging(short value);
        partial void OnVacationHoursChanged();

        public short SickLeaveHours
        {
            get
            {
                return this._SickLeaveHours;
            }
            set
            {
                this.OnSickLeaveHoursChanging(value);
                this._SickLeaveHours = value;
                this.OnSickLeaveHoursChanged();
                this.OnPropertyChanged("SickLeaveHours");
            }
        }             
        private short _SickLeaveHours;
        partial void OnSickLeaveHoursChanging(short value);
        partial void OnSickLeaveHoursChanged();

        public bool CurrentFlag
        {
            get
            {
                return this._CurrentFlag;
            }
            set
            {
                this.OnCurrentFlagChanging(value);
                this._CurrentFlag = value;
                this.OnCurrentFlagChanged();
                this.OnPropertyChanged("CurrentFlag");
            }
        }             
        private bool _CurrentFlag;
        partial void OnCurrentFlagChanging(bool value);
        partial void OnCurrentFlagChanged();

        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }             
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();

        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }             
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();

        public Contact Contact
        {
            get
            {
                return this._Contact;
            }
            set
            {
                this._Contact = value;
                this.OnPropertyChanged("Contact");
            }
        }             
        private Contact _Contact;

        public global::System.Data.Services.Client.DataServiceCollection<Employee> Employee1
        {
            get
            {
                return this._Employee1;
            }
            set
            {
                this._Employee1 = value;
                this.OnPropertyChanged("Employee1");
            }
        }             
        private global::System.Data.Services.Client.DataServiceCollection<Employee> _Employee1 = new global::System.Data.Services.Client.DataServiceCollection<Employee>(null, global::System.Data.Services.Client.TrackingMode.None);

        public Employee Employee2
        {
            get
            {
                return this._Employee2;
            }
            set
            {
                this._Employee2 = value;
                this.OnPropertyChanged("Employee2");
            }
        }             
        private Employee _Employee2;

        public global::System.Data.Services.Client.DataServiceCollection<EmployeePayHistory> EmployeePayHistories
        {
            get
            {
                return this._EmployeePayHistories;
            }
            set
            {
                this._EmployeePayHistories = value;
                this.OnPropertyChanged("EmployeePayHistories");
            }
        }             
        private global::System.Data.Services.Client.DataServiceCollection<EmployeePayHistory> _EmployeePayHistories = new global::System.Data.Services.Client.DataServiceCollection<EmployeePayHistory>(null, global::System.Data.Services.Client.TrackingMode.None);

        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    
    [global::System.Data.Services.Common.EntitySetAttribute("EmployeePayHistories")]    
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID", "RateChangeDate")]
    public partial class EmployeePayHistory : global::System.ComponentModel.INotifyPropertyChanged
    {
        public static EmployeePayHistory CreateEmployeePayHistory (int employeeID , global::System.DateTime rateChangeDate , decimal rate , byte payFrequency , global::System.DateTime modifiedDate)
        {
            EmployeePayHistory employeepayhistory = new EmployeePayHistory();
            employeepayhistory.EmployeeID = employeeID;
            employeepayhistory.RateChangeDate = rateChangeDate;
            employeepayhistory.Rate = rate;
            employeepayhistory.PayFrequency = payFrequency;
            employeepayhistory.ModifiedDate = modifiedDate;
            return employeepayhistory;
        }
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
                this.OnPropertyChanged("EmployeeID");
            }
        }             
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();

        public global::System.DateTime RateChangeDate
        {
            get
            {
                return this._RateChangeDate;
            }
            set
            {
                this.OnRateChangeDateChanging(value);
                this._RateChangeDate = value;
                this.OnRateChangeDateChanged();
                this.OnPropertyChanged("RateChangeDate");
            }
        }             
        private global::System.DateTime _RateChangeDate;
        partial void OnRateChangeDateChanging(global::System.DateTime value);
        partial void OnRateChangeDateChanged();

        public decimal Rate
        {
            get
            {
                return this._Rate;
            }
            set
            {
                this.OnRateChanging(value);
                this._Rate = value;
                this.OnRateChanged();
                this.OnPropertyChanged("Rate");
            }
        }             
        private decimal _Rate;
        partial void OnRateChanging(decimal value);
        partial void OnRateChanged();

        public byte PayFrequency
        {
            get
            {
                return this._PayFrequency;
            }
            set
            {
                this.OnPayFrequencyChanging(value);
                this._PayFrequency = value;
                this.OnPayFrequencyChanged();
                this.OnPropertyChanged("PayFrequency");
            }
        }             
        private byte _PayFrequency;
        partial void OnPayFrequencyChanging(byte value);
        partial void OnPayFrequencyChanged();

        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }             
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();

        public Employee Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this._Employee = value;
                this.OnPropertyChanged("Employee");
            }
        }             
        private Employee _Employee;

        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    
    [global::System.Data.Services.Common.EntitySetAttribute("Contacts")]    
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ContactID")]
    public partial class Contact : global::System.ComponentModel.INotifyPropertyChanged
    {
        public static Contact CreateContact (int contactID , bool nameStyle , string firstName , string lastName , int emailPromotion , string passwordHash , string passwordSalt , global::System.Guid rowguid , global::System.DateTime modifiedDate)
        {
            Contact contact = new Contact();
            contact.ContactID = contactID;
            contact.NameStyle = nameStyle;
            contact.FirstName = firstName;
            contact.LastName = lastName;
            contact.EmailPromotion = emailPromotion;
            contact.PasswordHash = passwordHash;
            contact.PasswordSalt = passwordSalt;
            contact.rowguid = rowguid;
            contact.ModifiedDate = modifiedDate;
            return contact;
        }
        public int ContactID
        {
            get
            {
                return this._ContactID;
            }
            set
            {
                this.OnContactIDChanging(value);
                this._ContactID = value;
                this.OnContactIDChanged();
                this.OnPropertyChanged("ContactID");
            }
        }             
        private int _ContactID;
        partial void OnContactIDChanging(int value);
        partial void OnContactIDChanged();

        public bool NameStyle
        {
            get
            {
                return this._NameStyle;
            }
            set
            {
                this.OnNameStyleChanging(value);
                this._NameStyle = value;
                this.OnNameStyleChanged();
                this.OnPropertyChanged("NameStyle");
            }
        }             
        private bool _NameStyle;
        partial void OnNameStyleChanging(bool value);
        partial void OnNameStyleChanged();

        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }             
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();

        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }             
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();

        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                this._MiddleName = value;
                this.OnMiddleNameChanged();
                this.OnPropertyChanged("MiddleName");
            }
        }             
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();

        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }             
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();

        public string Suffix
        {
            get
            {
                return this._Suffix;
            }
            set
            {
                this.OnSuffixChanging(value);
                this._Suffix = value;
                this.OnSuffixChanged();
                this.OnPropertyChanged("Suffix");
            }
        }             
        private string _Suffix;
        partial void OnSuffixChanging(string value);
        partial void OnSuffixChanged();

        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
                this.OnPropertyChanged("EmailAddress");
            }
        }             
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();

        public int EmailPromotion
        {
            get
            {
                return this._EmailPromotion;
            }
            set
            {
                this.OnEmailPromotionChanging(value);
                this._EmailPromotion = value;
                this.OnEmailPromotionChanged();
                this.OnPropertyChanged("EmailPromotion");
            }
        }             
        private int _EmailPromotion;
        partial void OnEmailPromotionChanging(int value);
        partial void OnEmailPromotionChanged();

        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }             
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();

        public string PasswordHash
        {
            get
            {
                return this._PasswordHash;
            }
            set
            {
                this.OnPasswordHashChanging(value);
                this._PasswordHash = value;
                this.OnPasswordHashChanged();
                this.OnPropertyChanged("PasswordHash");
            }
        }             
        private string _PasswordHash;
        partial void OnPasswordHashChanging(string value);
        partial void OnPasswordHashChanged();

        public string PasswordSalt
        {
            get
            {
                return this._PasswordSalt;
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this._PasswordSalt = value;
                this.OnPasswordSaltChanged();
                this.OnPropertyChanged("PasswordSalt");
            }
        }             
        private string _PasswordSalt;
        partial void OnPasswordSaltChanging(string value);
        partial void OnPasswordSaltChanged();

        public string AdditionalContactInfo
        {
            get
            {
                return this._AdditionalContactInfo;
            }
            set
            {
                this.OnAdditionalContactInfoChanging(value);
                this._AdditionalContactInfo = value;
                this.OnAdditionalContactInfoChanged();
                this.OnPropertyChanged("AdditionalContactInfo");
            }
        }             
        private string _AdditionalContactInfo;
        partial void OnAdditionalContactInfoChanging(string value);
        partial void OnAdditionalContactInfoChanged();

        public global::System.Guid rowguid
        {
            get
            {
                return this._rowguid;
            }
            set
            {
                this.OnrowguidChanging(value);
                this._rowguid = value;
                this.OnrowguidChanged();
                this.OnPropertyChanged("rowguid");
            }
        }             
        private global::System.Guid _rowguid;
        partial void OnrowguidChanging(global::System.Guid value);
        partial void OnrowguidChanged();

        public global::System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }             
        private global::System.DateTime _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.DateTime value);
        partial void OnModifiedDateChanged();

        public global::System.Data.Services.Client.DataServiceCollection<Employee> Employees
        {
            get
            {
                return this._Employees;
            }
            set
            {
                this._Employees = value;
                this.OnPropertyChanged("Employees");
            }
        }             
        private global::System.Data.Services.Client.DataServiceCollection<Employee> _Employees = new global::System.Data.Services.Client.DataServiceCollection<Employee>(null, global::System.Data.Services.Client.TrackingMode.None);

        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;        
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    
}
    