//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntiies
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract()]
    public partial class AddressDto : UIPaging
    {
        [Key()] 
        [Required] 
        [DataMember()] public int AddressID  {get; set; }
     
        [Required] 
        [DataMember()] public string AddressLine1  {get; set; }
        [DataMember()] public string AddressLine2  {get; set; }
     
        [Required] 
        [DataMember()] public string City  {get; set; }
     
        [Required] 
        [DataMember()] public int StateProvinceID  {get; set; }
     
        [Required] 
        [DataMember()] public string PostalCode  {get; set; }
     
        [Required] 
        [DataMember()] public System.Guid rowguid  {get; set; }
     
        [Required] 
        [DataMember()] public System.DateTime ModifiedDate  {get; set; }
    }
}
