//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntiies.DTO
{
    using System;using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract()]
    public partial class ContactDto : UIPaging
    {
        [Key()] 
        [Required] 
        [DataMember] 
        public int ContactID  {get; set; }
     
        [Required] 
        [DataMember] 
        public bool NameStyle  {get; set; }
        [DataMember] 
        public string Title  {get; set; }
     
        [Required] 
        [DataMember] 
        public string FirstName  {get; set; }
        [DataMember] 
        public string MiddleName  {get; set; }
     
        [Required] 
        [DataMember] 
        public string LastName  {get; set; }
        [DataMember] 
        public string Suffix  {get; set; }
        [DataMember] 
        public string EmailAddress  {get; set; }
     
        [Required] 
        [DataMember] 
        public int EmailPromotion  {get; set; }
        [DataMember] 
        public string Phone  {get; set; }
     
        [Required] 
        [DataMember] 
        public string PasswordHash  {get; set; }
     
        [Required] 
        [DataMember] 
        public string PasswordSalt  {get; set; }
        [DataMember] 
        public string AdditionalContactInfo  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.Guid rowguid  {get; set; }
     
        [Required] 
        [DataMember] 
        public System.DateTime ModifiedDate  {get; set; }
    
        [DataMember] 
        public virtual Employee [] Employees { get; set; }
    
    }
}
