//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using IronFramework.Common.Data.EntityFramework;
    
    [DataContract]
    public partial class EmployeePayHistory : IEntity
    {
        [DataMember]
        public int EmployeeID { get; set; }
        [DataMember]
        public System.DateTime RateChangeDate { get; set; }
        [DataMember]
        public decimal Rate { get; set; }
        [DataMember]
        public byte PayFrequency { get; set; }
        [DataMember]
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    
        #region IEntity Members
    
        public State State { get; set; }
    
        #endregion
    }
}
